import "@/styles/globals.scss";
import { Inter, Nunito } from "next/font/google";

const nunito = Nunito({
  subsets: ["latin-ext"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang="pl">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
